[project]
name = "sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "ollama>=0.4.8",
    "unicorn>=2.1.3",
    "uvicorn>=0.34.2",
]
